### ISSUE TITLE
[meta] Gatling limitations & improvements

### ISSUE THREAD

**Issue by dmlemeshko** [elastic/kibana-load-testing#265]
This issue collects current problems, limitations and possible improvements related to Gatling tool.

We need to do thorough research in this area to have more ideas around tool & environment tuning so that we minimize the noise introduced by Gatling itself. 

- [ ] Investigate socket reuse in Gatling (ephemeral port depletion) 
- [ ] Review official OS tuning [guide](https://gatling.io/docs/gatling/reference/current/core/operations/)
- [ ] Research for Elasticsearch connector to ingest test results, Gatling has [grahite sender](https://github.com/gatling/gatling/tree/main/gatling-graphite/src/test/scala/io/gatling/graphite/sender) , [docs](https://gatling.io/docs/gatling/guides/realtime_monitoring/)
